# Site settings
title: 罗腾展的个人博客
email: 1720608970@qq.com
description: > # this means to ignore newlines until "baseurl:"
  罗腾展的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.baotouzhai.com" # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Luo Teng Zhan
twitter:
  username: xiaomi

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter: xiaomi
# weibo:    ID
github: xiaomijiayou
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: http://xiaomijiayou.github.io/assets/img/touxiang.jpg
favicon: http://xiaomijiayou.github.io/assets/img/touxiang.jpg

# disqus 设置
disqus:
  shortname: suyan-zh

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

